### ISSUE TITLE
didn't recognize home directory shortcut when creating datavault 

### ISSUE THREAD

**Issue by joshm-3b6b58** [maffoo/scalabrad#2]
I don't know if this is a manager issue or a datavault server issue, but when I tried to create a new datavault in my home directory ~/DataVault, it didn't work. I had to give the full file path: /Users/mutus/DataVault then it worked just fine.

**Comment by maffoo** [comment]
Expansion of `~` is really a shell-specific thing, not something that happens when dealing with file paths in general. Also, given that this would expand differently depending on which user you run the server as, I think it's probably better to require the explicit path.

I am curious though how this happened; did you start the data vault and it asked for a path, or did you set the path in the registry and then the server failed to start? In the former case, we _could_ modify the data vault to expand the path before it writes it to the registry (https://docs.python.org/2/library/os.path.html#os.path.expanduser) though we should create an issue on the servers repo.

**Comment by joshm-3b6b58** [comment]
It was the former case, I started the datavault for the first time and it asked for a path. I wasn't able to figure out how to use the regsitry (as per my other issue)

**Comment by maffoo** [comment]
see martinisgroup/servers#144
