### ISSUE TITLE
NullPointerException when copying registry folders

### ISSUE THREAD

**Issue by pomalley** [maffoo/scalabrad#6]
Trying to copy one of Julian's daily qubit registries to my folder.

![image](https://cloud.githubusercontent.com/assets/1106276/7542770/773b5a34-f574-11e4-9ed1-6fe0f229852a.png)

It only copies directory q1 and then errors. I'm guessing this error is due to scalabrad because of the java exception.

**Comment by maffoo** [comment]
out of curiosity, is this repeatable?

**Comment by pomalley** [comment]
It errors for me every time I try to copy a directory with a subdirectory in it.

**Comment by maffoo** [comment]
This should now be fixed in version 0.2.0-M7. It turned out to be a problem with handling a call to `cd` with no arguments like `reg.cd()` which is supposed to just return the current directory path. We don't really do that anywhere, except in the registry editor when copying directories recursively. Go figure. If you can't immediately upgrade the manager, I've also put up a build of the registry editor on the skynet software share that doesn't make this call, and so will work with the M6 version. It's version 1.0.2-fix in the labrad directory.
