### ISSUE TITLE
Running scalabrad manager

### ISSUE THREAD

**Issue by zibrov-zlobin** [maffoo/scalabrad#9]
I am currently running the LabRAD manager by:
sbt> run --password="pass"

sbt then prompts we which main class should it run, the Manager or the Migrate.
is this the right way of running it? Or is there a way of storing the port,password etc in a configuration file? Is there a way to choose the default main class to run?

**Comment by maffoo** [comment]
To choose the main class, use `runMain` instead of `run`:

```
sbt> runMain org.labrad.manager.Manager --password="pass"
```

If you want to configure things like the password the way to do that is to put them in environment variables, e.g. set `LABRADPASSWORD` for the password. There's no way to set this in a config file at the moment, but feel free to open an issue if you'd prefer to configure things that way.

When you're actively developing the manager, it's fine to run from sbt, but for a running system, you probably want to use a pre-built package. We're publishing these packages through bintray, e.g. https://bintray.com/artifact/download/maffoo/generic/scalabrad-0.2.0-M8.tar.gz is a recent build. Download and unpack this and in the enclosed bin directory you'll find scripts for starting the manager (as well as the registry migration tool, and perhaps more binaries in the future). You can add this to your path and run from there. In particular this avoids the overhead of starting up sbt itself, and also means you don't need a JDK on the system, just a (java 8) JRE.

**Comment by maffoo** [comment]
I created a labrad organization on bintray and we'll use that for distributing scalabrad binaries from now on. Also added a note about getting and running this in the README.

**Comment by DanielSank** [comment]
@maffoo let's try to put any and all information on tickets like this one into the wiki or readme files. I'd go as far as to say we should not give instructions in the ticket tracker that we're absolutely forced to put the docs where they belong.

**Comment by maffoo** [comment]
agreed. good call.
