### ISSUE TITLE
LabRAD upgrade issue: directory .dir extension, can one avoid it?

### ISSUE THREAD

**Issue by xiaoyuejin** [maffoo/scalabrad#95]
I am a user of the old Delphi LabRAD manager for years. Now I am trying to upgrade to the new scalabrad manager, but backward compatibility is of my highest priority. For newer users who never touched the Delphi version, these issues might not be interesting…

Since I have multiple problems, I will split them to different issues.

Test platform: Windows 7 x64, Java 8 up to date, Python 2.7, pylabrad up to date, without footprint of previous versions of LabRAD.

Issue with directory names: I noticed is that the new manager ignores any directory if it does not have an extension ‘.dir’ with it (this include subdirectories in registry and data). What is the idea behind this setting? Is there a way to switch off this setting so that all the directories will be recognized? I have several thousands of subdirectories in my old registry and data directories and I don’t really want to add extensions to them.

Added: Now that I played around with the new version of LabRAD, I start to wonder if the .dir issue should be posted here, or rather in the pylabrad repo. Please someone tell me...

**Comment by maffoo** [comment]
I'm not sure what the issue is here because the old delphi registry also added a `.dir` suffix to registry folder names on the file system. This behavior should be identical in the scala manager. The original reason for this was so that you can have a key and subfolder with the same name in a registry directory (if you really wanted to) and the resulting files stored on disk would get different names, as required by most file systems. But as I said, this behavior should be identical between the old delphi manager and the scalabrad manager.

As for the data vault, it uses a similar scheme to name files in its storage folder, but that is totally up to the data vault and independent of which manager implementation you are using.

Also note that the registry and data vault were both designed to be the _only_ programs touching their respective storage directories. If you are putting other files in there using other programs, then you may see unexpected behavior, so I would advise against that (reading registry or data vault files _might_ work, but should definitely not write or modify any files, except through the registry or datavault servers).
